### ISSUE TITLE
provide a way to pass ca certs instead of using self signed certs for https requests

### ISSUE THREAD

**Issue by sidtagirisa** [opticdev/optic#1121]
right now we are trying to intercept traffic of an environment that is rejecting because of self-signed certificate and disabling that check is not an option in that server, so please let me know if there is a way I can provide certs to be used instead of self-signed certificates being created in your code.

**Comment by sidtagirisa** [comment]
After some looking through, found an alternative for this as well.

option to provide [ignoreHostHttpsErrors](https://github.com/httptoolkit/mockttp/blob/b9188140f7d9f8d2f68d1f85b7bf1e56a66e953f/src/rules/requests/request-handlers.ts#L468 ) option [here](https://github.com/opticdev/optic/blob/develop/workspaces/cli-shared/src/httptoolkit-capturing-proxy.ts#L109) in your code would be awesome

Please let me know if this is feasible.

**Comment by LouManglass** [comment]
Hi @sidtagirisa,

Would you be able to provide some of the errors for our reference? I want to make sure we are solving the right problem. A set of known errors will help us assure it gets fixed, fully, in the correct place.

If that's not feasible, I understand. We'll look into this request, as it makes sense to provide as an option. We can also chat further to find other interim workarounds or solutions that will fit your application, if that's helpful.

**Comment by sidtagirisa** [comment]
hi, @LouManglass found a way to pass the certificate and it is working. 

Since you are using mockttp and they are honoring this env: NODE_EXTRA_CA_CERTS, if we set NODE_EXTRA_CA_CERTS='path to pem file' it is not throwing self-signed cert error.

**Comment by sidtagirisa** [comment]
I would love to provide any additional details if you still require me to, please let me know.

**Comment by LouManglass** [comment]
@sidtagirisa Oh, this is great, thanks for the follow-up! To clarify: you set the `NODE_EXTRA_CA_CERTS` environment variable to the path to the PEM file for the server certificate, correct? That way, mockttp trusts your application, and the rest of the chain works for you?

If that's true, I think I have enough to get this added to our documentation this week, though I'd appreciate the opportunity to see your work in action. If you have some time, here's my [calendly](https://calendly.com/d/wd8f-979j/30-minute-meeting), and I can also be flexible around those hours with some notice. Otherwise, I'll dig into the documentation and reach out with any further questions as they come up.

**Comment by sidtagirisa** [comment]
@LouManglass Yes, that’s correct. 

Sure, I can show you it in action, I will setup a call probably sometime next week.

In the meantime if you have anymore questions please don’t hesitate to reach out. 

Also, the latest documentation, it is so much better than last year, nice work on that ✌🏼. Thanks for this library, it helps a lot.

**Comment by LouManglass** [comment]
@sidtagirisa Thanks for the kind words, I'll pass them along to the team! We're always looking to make our documentation better, and we appreciate that you noticed.

And also thanks for your time, I'll keep an eye out for that appointment.
