### ISSUE TITLE
captures size

### ISSUE THREAD

**Issue by siddtagirisa** [opticdev/optic#1134]
It would be nice to have a option to delete captures which are not necessary anymore as the size is growing super big and showing the diff is taking a long time than it should.

Please let me know if I can do that already.

**Comment by sidtagirisa** [comment]
@LouManglass Thanks for the suggestion, I wasn't sure manual clean up was a safe option, will do that until there is a option. No worries.

**Comment by sidtagirisa** [comment]
hi @LouManglass I want to understand is there a way to rotate captures for each day without restarting? I observe right now that capture is getting rotated once we restart the service.

**Comment by LouManglass** [comment]
@siddtagirisa No, there is currently no option to rotate captures while the service is running. We are looking more generally into how we set these capture boundaries and service sessions, as we know that can be improved. Stay on the lookout for improvements to the workflow to help keep captures from getting too large in any one session, and to keep old captures from piling up.

**Comment by sidtagirisa** [comment]
sure @LouManglass I have a suggestion on this. I observed your current diff engine is very fast on small captures. 

So, instead of saving entire captures on disk and running diff engine when user opens browser, it might help if you run diff engine periodically in the background, save it in a file and purge the captures which diff is captured. It might improve the workflow of optic a lot.

**Comment by LouManglass** [comment]
That's a great idea, thanks! We are looking generally in that direction: making smaller units of work to minimize the impact of large samples, and reducing the scope of what we put in front of users at any given time. We definitely want to make the workflow easier for everyone, and appreciate the feedback.
