### ISSUE TITLE
Cannot Create Complex Schema Using allOf

### ISSUE THREAD

**Issue by ka-tran** [opticdev/optic#1558]
Hello. My team has recently started the use of optic diff, but we seem to have come across something that is causing issues for our files to compare. We are attempting inheritance using the allOf keyword as [shown here in swagger docs](https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/), but running optic diff throws an error regarding this.

For example using the [optic playground](https://www.useoptic.com/docs/playground) I've added a small schema Dog which will reference the pre-existing Pet

``` 
Dog:
  allOf:
    - $ref: '#/components/schemas/Pet'
  properties:
    color:
      type: string
  required:
    - color
```

The returned error is as such:

```
main branch openapi is invalid yaml
invalid openapi: components > schemas > Dog schema with anyOf cannot also include keywords: properties, required /components/schemas/Dog
```

But this same schema added to the [swagger playground](https://editor.swagger.io/) does not throw an error, and works as intended.

Some screenshots provided:

<img width="1406" alt="Screenshot 2023-01-25 at 6 12 42 PM" src="https://user-images.githubusercontent.com/105816510/214742695-9d0d39b1-f5b4-4dd8-8d88-d2baac32bef6.png">
<img width="935" alt="Screenshot 2023-01-25 at 6 12 53 PM" src="https://user-images.githubusercontent.com/105816510/214742701-6644ed5b-2685-4153-863e-3ec71f2e6f40.png">

Any help or guidance is appreciated! Thank you so much!

**Comment by acunniffe** [comment]
Hey @ka-tran thanks for opening the issue. 

I'm not sure if the example schema you provided is actually valid JSON Schema. If you look at the example from the Swagger docs you linked, you will notice they have object/properties as a child of `allOf`. 

This means that `ExtendedErrorModel` must validate against both the referenced `BasicErrorModel` and the inlined schema. 

<img width="690" alt="Screenshot 2023-01-26 at 7 36 41 AM" src="https://user-images.githubusercontent.com/5900338/214837175-bcc6eb40-ce98-4600-b8e3-bf3c9ab56ad6.png">

In your example this would look like. I also noticed you were missing `type: object` which is required everywhere you define `properties: {}`
```yaml
Dog:
  allOf:
    - $ref: '#/components/schemas/Pet'
    - type: object
      properties:
        color:
          type: string
      required:
       - color
```

It is really subtle and you are not the first person I have worked with that ran into this issue. The errors you get from Optic are trying to tell you what the problem is, but it could be clearer. 

Re: Swagger Editor -- I am really not sure why they are accepting the invalid JSON Schema. Most OpenAPI tools get stuck making the choice between being strict to the spec or allowing looser inputs. If you are on-boarding a company with hundreds of spec and many of them do not follow the spec perfectly, it can slow down adoption or maybe even lose the deal.  My guess is that someone made the choice to be less strict, but I don't know for sure. Could be technical oversight. 

We (Optic) are currently focussing on being strict to OpenAPI so the specs we help teams make can be used by other tools. 

Does that make sense? 

If you are using this allOf pattern in a lot of places maybe we can help you write a script to "fix" the spec.

**Comment by ka-tran** [comment]
Hey @acunniffe ! Thank you very much for the response!

I've attempted to put the "properties" and "required" nested inside of the allOf keyword, and it does get passed the error logs to call optic diff, but I'm getting a different issue if you might know more. So with the properties and required being nested, it looks like something is being ignored.

If you replace the PUT /pet '200' return response content with the new Dog schema we've added in the optic playground (main), the diff check says everything inside of Pet schema is missing in addition to the Dog's new 'color' property. The missing color error is expected as that is our new change that the feature/example doesn't possess, but I'm not sure why everything else is missing too. The same 'removed' properties are shown to be added in towards the bottom also, if I'm reading the web tool correctly, so technically they are there?

<img width="1006" alt="Screenshot 2023-01-26 at 11 53 12 AM" src="https://user-images.githubusercontent.com/105816510/214936606-b37762c8-6d95-45a1-ad1e-1715107e4bbe.png">

<img width="999" alt="Screenshot 2023-01-26 at 11 53 19 AM" src="https://user-images.githubusercontent.com/105816510/214936624-4a442666-4a1a-48d9-be50-66857416fcfa.png">

Thank you again for the help! Optic is a very powerful tool and we're still learning what we can in regards to swagger as well

**Comment by ka-tran** [comment]
Hi again, so I think I know the issue with what I'm trying to do. It looks like both files MUST include allOf if that's what I plan to use, as that's what makes them match. 

I was facing this issue because the new file I'm trying to compare with our main file is auto-generated, and due to some rules with the generation the new file doesn't use allOf, and instead combines the refs into one large schema instead. I was incorrectly assuming that it wouldn't matter, as technically they mean the same thing. But as a tool specific to finding the differences between my two files, I see why errors are being thrown. I think this closes out my issue here, and I'll need to figure out some workarounds.

Thanks again for the help! If Optic team has any additional advice regarding this, it would be appreciated :) Otherwise, take care!
