### ISSUE TITLE
Cleanly stopping and starting the Optic Daemon

### ISSUE THREAD

**Issue by devashish2203** [opticdev/optic#230]
Hi

I'm trying out optic for documenting my existing APIs. I could get it setup to capture my API requests which is great. I wanted to cleanly shut down the Optic Daemon when I'm not using it but could not find a way to shut it down cleanly.

Basically in my workflow I run
`api run <task_name>`

Go through my test cases and capture the APIs being used.
Ctrl-C the api run task to stop my app.

Look at the Optic dashboard to review the diffs and  add/edit the API's captured

After this I still find that the following process keeps running on the system

```
/usr/bin/node /usr/lib/node_modules/@useoptic/cli/node_modules/@useoptic/cli-server/build/main
```

I would like to shut this down cleanly and be able to start it back up the next time I start testing, but could not find any way to do this.

**Comment by LouManglass** [comment]
@devashish2203 

`api daemon:stop` should handle that for you. `api daemon:start` as a side note also works, though it doesn't start any capture sessions and as such there is no context for the dashboard. If you want to review documentation later, `api spec` is the recommended path.

I just checked, and realized this isn't documented on the CLI. I'll take note of that for a future release.

**Comment by devashish2203** [comment]
Thanks! The above commands work.


To summarize 
Stop Daemon
`api daemon:stop`

Start Daemon
`api daemon:start`

Start capture
`api run <task_name>`

View Documentation
`api spec`

**Comment by LouManglass** [comment]
Right, though as a reminder: `api daemon:start` isn't recommended for general use. You should never have a scenario where you have to run that command. `api daemon:stop` is the only command you'll want from the daemon topic, for graceful dashboard shutdown.

The remaining commands are right on! They're also documented in the CLI (*e.g.* `api help run`) and in our [Optic documentation](https://docs.useoptic.com/) if you want to see them in action.

After further discussion internally, since the daemon topic isn't really meant to be user facing, we won't unhide the command at this time and will consider better flows for users that directly address end users' needs. `api daemon:stop` is safe to use, though we can improve the end of work flow.

**Comment by devashish2203** [comment]
Thanks for the clarification. I'll close the issue now.

**Comment by bethesque** [comment]
I had the same issue, and couldn't find any documentation on the NPM page or in the help.

```
The Optic CLI

VERSION
  @useoptic/cli/9.0.4 darwin-x64 node-v12.0.0

USAGE
  $ api [COMMAND]

COMMANDS
  check     Validate the correctness of a task in your optic.yml
  generate  export an OpenAPI 3.0.1 spec
  help      display help for api
  init      Add Optic to your API
  login     Login to Optic from the CLI
  logout    Logout from Optic
  run       Run a task from your optic.yml
  scripts   Run one of the scripts in your optic.yml file
  spec      Open your Optic API specification
  start     starts your API process behind an Optic proxy
```

I've been manually stopping the daemon by finding what process is running on port 34444 and killing it. I would have liked to see this documented somewhere. It seems very strange that it's apparently meant to be left running.
