### ISSUE TITLE
Optic throws an error when receiving multipart/form-data requests

### ISSUE THREAD

**Issue by mithodin** [opticdev/optic#2535]
**Describe the bug**
When uploading a file to an endpoint that takes a multipart/form-data request body, optic throws the error
```
[request body] '' does not match type object.
```

**To Reproduce**
1. Clone the minimal example at https://github.com/mithodin/optic-multipart-form-data-repro
2. Run `npm install`, then `npm run optic:test`
3. See error

**Expected behavior**
optic should pass successfully and report a compliant request body.

**Comment by niclim** [comment]
Thanks for the repro case - it looks like we aren't parsing form data / multipart form data and is currently being interpreted as a string (which is why it's saying `'' does not match type object`.

I believe this will need to be added here https://github.com/opticdev/optic/blob/main/projects/optic/src/commands/capture/patches/patchers/shapes/documented-bodies.ts#L224, and we'll need to pull in something to parse form / multipart form data here

**Comment by niclim** [comment]
Hi, version `0.53.21` now supports form data and multipart-form data - thanks for reporting and let us know if there's anything else you run into!
