### ISSUE TITLE
Optic crashes when reviewing diffs and documenting end points

### ISSUE THREAD

**Issue by PatrickCarmel** [opticdev/optic#260]
I was trying to document api endpoints, I had some different instances of optic running from a few days ago and it kept crashing when I was going to apply the changes to diffs on while creating documentation for an api request.

**Comment by LouManglass** [comment]
Hi @PatrickCarmel 

What version are you currently running? `api --version` will report that information.

Also, did you receive any error messages, either in the UI or on the command line, when these crashes occurred? If so, please send those along. If not, we can collect some debugging information.

**Comment by PatrickCarmel** [comment]
the version of optic I am running is: @useoptic/cli/8.1.1 darwin-x64 node-v10.16.3 and I didn't get any errors in the console. but it displayed a web page when I was editing diffs saying something had gone wrong, with steps on how to fix it such as refreshing or doing a debug Optic but I didn't get any screenshots.

**Comment by LouManglass** [comment]
Thanks for the details! We've fixed a few issues and made some improvements. My first suggestion would be upgrading to the latest (currently 8.2.8) with

`npm install --global @useoptic/cli`

Then giving it another shot. If you're still seeing an error, you can generate a debug report from the browser console with `debugOptic();` which will generate a .json file. If you'd prefer to send that directly to us instead of posting that on a GitHub Issue, let me know: we can support your preferred method of sending detailed Optic debugging data.
