### ISSUE TITLE
Unable to define API endpoints sharing a path

### ISSUE THREAD

**Issue by ViRb3** [opticdev/optic#425]
I am trying to define an API which has the following spec:
`/api/addons/:addon_id` - get addon info
`/api/addons/timestamp` - get addon database timestamp

Unless I'm missing something, Optic does not allow me to define the wildcard `:addon_id` but also have a static path `timestamp` - it marks them as the same endpoint and fails to resolve the response JSON conflicts, since the responses have nothing to do with each other - they're two completely separate endpoints. I am aware that this is not exactly a beautiful API spec, but it is unfortunately what I am working with. Any way to get this to work?

**Comment by LouManglass** [comment]
Hi @ViRb3 

Currently there's no way to define both a wildcard and a static path on the same route like that within the app. I can see how that would be a problem, and I imagine yours is not the only API that will run into this problem.

Would you please tell me more about the format of the `addon_id`? To handle this issue properly, we want to have more information on how we can better discern between IDs and static routes. The more information we have, the better we can address the issue.

In the mean time, I'll dig into a temporary workaround to get that route documented. We could ignore one of the routes, like `/api/addons/timestamp`, for the time being. The upside is we could document it later. The downside is that it wouldn't be documented until we resolve the issue. Let me know what you think, and I'll try a few other things here to see if we can get you a better workaround. I'll be in touch with more ideas this week.

**Comment by ViRb3** [comment]
Hello,

Thank you for response! The `addon_id` in my case is an integer, but I don't think that matters. The way I see it, Optic could allow you to define `/timestamp`, `/status`, etc., and if you then define a wildcard `/:addon_id`, it will just match everything that has not been explicitly defined like `/timestamp` and `/status`. Would this work, in your opinion?

**Comment by LouManglass** [comment]
That certainly is a possibility. We're trying to make learning your API as smooth a process as possible, and we want to make sure we not only get it right but also make it easy to use. Thanks for the thoughts, they're very helpful in getting us there.

**Comment by LouManglass** [comment]
Hi @ViRb3 ,

Currently, the only way to document the static paths in this case would be to document them all first, then document the paths that use a parameter. This isn't far off from your suggestion, where you could define the static paths and then the wildcard. The hurdle here is getting your specification back to a state where we can do this.

The quickest workaround right now would be to amend your specification to remove the parameterized definition, then to re-learn these routes with the static routes first and the parameterized route last. The easiest way to do so would be to send us your current specification file which we can patch properly and return to you. That assures the correct elements are set and that your specification will continue to work as expected.

The specification file will contain all your endpoints and the shape (but not field values) of your request and response traffic. If you'd prefer, you can email us for more information and a walkthrough. I'm lou@useoptic.com. If your project is open source, or a publicly available API (_e.g._ if it's the `https://addons-ecs.forgesvc.net` API from Issue 426), you can also attach your specification to this issue. The specification file is located in your project at .optic/api/specification.json.

I can amend the file so you may continue documenting for now. In the long-term, we are looking at ways of adding the ability to re-learn routes like this as a supported feature in Optic.

**Comment by ViRb3** [comment]
Hello,

I really appreciate the time and effort you are spending to help. I would happily send my spec so you can fix it, but I'm constantly experimenting and re-doing that spec (along with many others), so it wouldn't make sense if I have to ask you to patch it for me every time. I think both for me and anyone else who stumbles upon this edge case, it would be very helpful if you could write the patching steps so we could do it ourselves. Perhaps a separate topic in the docs, or a quick write-up here, I will be more than happy with either.

Thanks again

**Comment by LouManglass** [comment]
@ViRb3 

Each case is a bit different, and there's no general "do this one thing" remedy for all specification adjustments. Also, manually editing the specification file bypasses the built-in checks in the software. This means it's hard to give a solid, documented flow that works for any specification fix and also guards against causing side effects. That's why we're trying to bridge the gap manually until we can get a proper feature implemented in the dashboard.

That being said, I understand we don't have a great workaround currently, and I appreciate how much you're working with Optic. It's really cool to see all these different API experiments and specifications coming along, and I understand that it wouldn't make sense to reach out every time in your case. I'll try to put together some documentation for you over the next week as time allows so you aren't blocked by us.

In the mean time, you can add a [RequestRemoved` event](https://github.com/opticdev/optic/issues/55#issuecomment-578326126) to remove a given request from a spec. I don't think this will address your issue above (as we manage the paths as separate events, and I imagine it's going to be a bit more complicated in this case) but this may help you with other projects while I dig into this further.

**Comment by LouManglass** [comment]
@ViRb3 

I dug into this a bit. Due to the nature of the specification events we use to reconstruct the API, we'd need to clear out the entire parameterized endpoint and start over to document the static routes first. This involves manipulating not only requests, but the path specification and traffic shape information about the path. This isn't a simple task in a trivial case, and would be even more complex in a specification with many routes.

We're working on improvements to allow a static route to be specified after identifying a parameterized route, to avoid this issue in the future. The specific remedy isn't decided yet, and we're looking at a few options that can also serve other use cases as well in a sensible way.

In the mean time, there's not a great solution today. If you don't have a lot of details added to your documentation for this API, we do have a beta version of Optic available that has an automated batch learning capability. It would require re-learning the entire API, though you could learn all of the static routes in one pass, then all of the parameterized routes in one pass. It automatically detects things like optional fields, and saves you almost all of the manual clicking. If you don't have details documented already, this would be a faster fix than trying to manually edit parameterized routes.

Let me know if this works, and I can get you the latest beta instructions to give it a shot. In any case, you might find it helpful for learning future APIs as well.

**Comment by ViRb3** [comment]
Hey there @LouManglass

I suspected it would come to redoing my Optic spec, so I didn't even begin working on it yet. It would be more than perfect if I could use the new beta.

Thanks

**Comment by LouManglass** [comment]
@ViRb3 I think you'll have a great time with the new beta. I'm sorry that's the best solution we have for re-learning these endpoints, but overall I think this will be a big help to you in all your work.

Right now our latest version is beta build 18 on version 8.6.0, which you can install via npm with:

`npm install --global @useoptic/cli@8.6.0-beta.18`

While we've been testing this pretty thoroughly, it's still a beta and if you run into any rough edges please let us know. As a reminder, please document all the static routes in your first pass, then do parameterized routes in a second pass. The UI is a bit different in the beta, which lets you bulk document and auto-learn routes. We've tried to make it flow well, and if you run into any questions please reach out to me directly (lou@useoptic.com so you don't have to scroll up). As it's a beta, we don't have documentation ready to send so I'll help you directly.
