### ISSUE TITLE
Cannot install optic

### ISSUE THREAD

**Issue by Hussien47** [opticdev/optic#71]
<img width="1147" alt="Screen Shot 2020-03-12 at 4 58 12 AM" src="https://user-images.githubusercontent.com/54534163/76479913-510fae00-641e-11ea-87a9-6f369291f7b6.png">
 I'm trying to install the library but am stuck at installation.

**Comment by acunniffe** [comment]
Hey @Hussien47 — can you try installing node-gyp manually, then try installing Optic again

https://www.npmjs.com/package/node-gyp

If that works I’ll update the docs to make sure a node-gyp dependency is stated clearly.

**Comment by devdoshi** [comment]
@Hussien47 - did you upgrade your node version recently? Looks like you'll need to reinstall or rebuild @useoptic/cli - let me know if you still run into trouble.

**Comment by palmtop** [comment]
I have the same problem. I tried to install it on my Ubuntu 1804 server machine, it was not successfull, then I tried upgrading node and node-gyp but still not success. I tried it on another Ubuntu 1804 server, with a newly installed nodejs and here it did not work either.

I installed it on a Windows 10 machine, and the installation worked without any problem, I had only to change the Powershell script execution policy with `Set-ExecutionPolicy RemoteSigned -Scope LocalMachine` to have it executed. 

I have attached the full Linux npm install log, it seems that the registry-js package has problems with the global installation. 

What is strange, that as far I could guess this is a module to handle Windows registry, which I assume it is not needed on Linux.

When trying to install registry-js I could install it locally (without -g) but not globally.

**Comment by palmtop** [comment]
Update: I could install now it on the fresh nodejs machine :-)

There the only missing thing was build essentials.

So on my development machine there should be some other problem, probably its npm configuration is fully scrued up.

**Comment by acunniffe** [comment]
Hey @palmtop  -- glad you got it working. I'll update the docs tonight and make sure people know to install build-essentials as a pre-req on Linux. 

We're working on a version of Optic that can run via Docker CLI. Do you have Docker in your dev env?

**Comment by palmtop** [comment]
Hi thank you for the answer. In this concrete case I do not have docker, but I am using a lot of docker and it is a very good way to avoid installation problems. 

I did already a quick test in my developmet environment and it worked without any problems. 

Now I am a bit struggling, because my real task is to verify and update the documentation for an existing project. I do not want to install the whole development environment, and I am trying to setup an enviroment, where I could put optic in between the client and the backend, but it is not that easy without modifying the client and the backend.

**Comment by acunniffe** [comment]
Hey @palmtop -- 

Sounds like your needs line up with what we are working on this month. The team is finishing the development of lightweight optic-agents that can be deployed in staging, development, and production w/o bringing the whole development environment with them. 

Can you sign up for [Maintainer Office Hours](https://calendly.com/opticlabs/maintainer-office-hours). We want to learn about your use case and help you get set up. 

Closing this ticket since it's about an install issue.
